### ISSUE TITLE
Add Ember.Select example

### ISSUE THREAD

**Issue by george** [bazzel/ember-sample2#1]
I've learned a ton reading your Ember implementation and regularly recommend it on #emberjs.  Thank you!

If you have time, I'd love to see an implementation of Em.Select, particularly pulling data from another model.

Thanks again,

/g

**Comment by bazzel** [comment]
I added another ember sample app that does use the Em.Select. https://github.com/bazzel/ember-sample3

**Comment by george** [comment]
Brilliant, thanks!  You helped clarify a lot of the workflow for creating new model objects with associations.  I appreciate your work.
